---
site:
  title: "Service Administration Basics [Admin 101]"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::01-ps.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
