---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-ps"
      label: "Ps"
    - name: "02-kill"
      label: "Kill"
    - name: "03-service"
      label: "Service"
    - name: "04-systemctl"
      label: "Systemctl"
    - name: "05-restarting-services"
      label: "Restarting Services"

tabs:
  - name: ">_ root"
    url: /wetty/ssh/root
